In [36]:
import pandas as pd
import os
import numpy as np
from datetime import timedelta, datetime
from datetime import date

In [37]:
#  Examen

## 1) Crea un Dataframe de 10 registros y 6 columnas y consigue las 5 primeros y los 5 ultimos registros

dataFrame = pd.DataFrame(np.random.randint(1, 10,60).reshape(10,6))
dataFrame

print(dataFrame[:5])
print("\n")
print(dataFrame[5:])

0  1  2  3  4  5
0  6  5  3  7  1  6
1  8  6  8  8  5  6
2  6  3  9  2  4  8
3  9  8  9  1  8  6
4  4  3  7  2  7  8


   0  1  2  3  4  5
5  8  1  7  1  3  8
6  6  4  7  3  2  5
7  2  9  6  5  8  8
8  4  6  8  4  5  3
9  4  2  8  5  4  7


In [41]:

## 2) Crear un dataframe pasando un arreglo de numpy de 6 x 4 con una fecha como indice y con columnas A, B, C, D randomico

#```
#                   A         B         C         D
#2013-01-01  0.469112 -0.282863 -1.509059 -1.135632
#2013-01-02  1.212112 -0.173215  0.119209 -1.044236
#2013-01-03 -0.861849 -2.104569 -0.494929  1.071804
#2013-01-04  0.721555 -0.706771 -1.039575  0.271860
#2013-01-05 -0.424972  0.567020  0.276232 -1.087401
#2013-01-06 -0.673690  0.113648 -1.478427  0.524988
#```

dataFrame2 = pd.DataFrame(np.random.randint(1, 10,24).reshape(6,4), columns=list('ABCD'),index = [datetime.today().date(), datetime.today().date() - timedelta(days=1) ,datetime.today().date() - timedelta(days=2),datetime.today().date() - timedelta(days=3), datetime.today().date() - timedelta(days=4), datetime.today().date() - timedelta(days=5)])
dataFrame2



A  B  C  D
2020-09-22  7  7  6  1
2020-09-21  4  9  8  6
2020-09-20  8  4  2  8
2020-09-19  5  3  3  1
2020-09-18  6  3  2  7
2020-09-17  3  3  9  5

In [43]:
## 4) Crear un Dataframe con 10 registros y 6 columnas y con una propiedad del Dataframe mostrar las columnas, con otro comando mostrar los valores.


dataFrame4 = pd.DataFrame(np.random.randint(1, 10,60).reshape(10,6), columns=list('abcdef'))
print('Dataframe:')
print(dataFrame4)

print('Columnas:')
print(dataFrame4.columns)

print('\nValores:')
print(dataFrame4.values)

Dataframe:
   a  b  c  d  e  f
0  3  4  7  8  1  3
1  5  4  9  4  5  7
2  5  7  4  5  3  1
3  4  1  4  7  3  7
4  2  1  7  4  2  3
5  8  3  1  4  2  1
6  5  4  1  3  1  8
7  4  7  4  4  4  8
8  1  5  2  6  1  4
9  9  9  5  1  2  2
Columnas:
Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

Valores:
[[3 4 7 8 1 3]
 [5 4 9 4 5 7]
 [5 7 4 5 3 1]
 [4 1 4 7 3 7]
 [2 1 7 4 2 3]
 [8 3 1 4 2 1]
 [5 4 1 3 1 8]
 [4 7 4 4 4 8]
 [1 5 2 6 1 4]
 [9 9 5 1 2 2]]


In [44]:
## 5) Crear un Dataframe con 10 registros y 6 columnas y con una funcion del Dataframe describir estadisticamente el Dataframe

dataFrame5 = pd.DataFrame(np.random.randint(1, 10,60).reshape(10,6), columns=list('abcdef'))
dataFrame5.describe()

a          b          c          d          e          f
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000
mean    6.800000   3.400000   6.200000   3.800000   5.200000   3.700000
std     1.932184   1.505545   2.347576   2.440401   2.859681   2.002776
min     4.000000   1.000000   1.000000   1.000000   1.000000   1.000000
25%     5.250000   2.250000   5.250000   2.250000   3.500000   2.000000
50%     7.500000   3.500000   7.000000   3.000000   5.500000   3.500000
75%     8.000000   4.000000   7.750000   4.000000   6.750000   5.000000
max     9.000000   6.000000   9.000000   9.000000   9.000000   7.000000

In [45]:

## 6) Crear un Dataframe con 10 registros y 6 columnas y con una funcion del Dataframe transponer los datos

dataFrame6 = pd.DataFrame(np.random.randint(1, 10,60).reshape(10,6), columns=list('abcdef'))
print('Dataframe')
print(dataFrame6)

print('\n Transpuesta')
print(dataFrame6.transpose())


Dataframe
   a  b  c  d  e  f
0  8  6  2  2  9  8
1  2  8  8  4  8  5
2  3  3  7  6  6  4
3  9  4  2  6  3  5
4  1  2  8  3  2  5
5  2  8  5  9  7  2
6  8  3  5  4  5  4
7  1  3  7  7  9  3
8  5  9  9  7  9  8
9  4  9  2  2  9  6

 Transpuesta
   0  1  2  3  4  5  6  7  8  9
a  8  2  3  9  1  2  8  1  5  4
b  6  8  3  4  2  8  3  3  9  9
c  2  8  7  2  8  5  5  7  9  2
d  2  4  6  6  3  9  4  7  7  2
e  9  8  6  3  2  7  5  9  9  9
f  8  5  4  5  5  2  4  3  8  6


In [47]:
## 7) Crear un Dataframe con 10 registros y 6 columnas y Ordenar el dataframe 1 vez por cada columna, ascendente y descendente

dataFrame7 = pd.DataFrame(np.random.randint(1, 10,60).reshape(10,6), columns=list('ABCDEF'))
print(dataFrame7)

dataFrame7 = dataFrame7.sort_values(['A','C','E'],ascending=True)
dataFrame7 = dataFrame7.sort_values(['B','D','F'],ascending=False)
print("Ordenado")
print(dataFrame7)

A  B  C  D  E  F
0  2  4  7  6  3  4
1  2  6  3  5  3  9
2  5  2  8  6  7  8
3  2  1  3  2  1  3
4  1  9  6  2  4  8
5  5  4  1  1  2  1
6  1  9  8  1  5  6
7  4  8  2  1  3  7
8  8  6  3  7  4  2
9  8  6  3  1  5  7
Ordenado
   A  B  C  D  E  F
4  1  9  6  2  4  8
6  1  9  8  1  5  6
7  4  8  2  1  3  7
8  8  6  3  7  4  2
1  2  6  3  5  3  9
9  8  6  3  1  5  7
0  2  4  7  6  3  4
5  5  4  1  1  2  1
2  5  2  8  6  7  8
3  2  1  3  2  1  3


In [50]:
## 8) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y seleccionar en un nuevo Dataframe solo los valores mayores a 7
dataFrame8 = pd.DataFrame(np.random.randint(1, 11,60).reshape(10,6), columns=list('ABCDEF'))
dataFrameFiltrado = dataFrame8.where(dataFrame8>7)
dataFrameFiltrado


A     B     C     D     E     F
0   NaN  10.0   NaN  10.0   9.0   9.0
1   NaN   NaN  10.0   NaN   8.0   NaN
2  10.0   NaN   NaN   NaN   8.0   NaN
3  10.0   NaN   NaN   NaN   NaN   NaN
4   NaN   NaN   NaN   NaN   9.0  10.0
5   NaN   NaN   NaN   NaN   NaN   NaN
6   NaN   NaN  10.0   NaN   NaN   NaN
7   NaN   NaN   NaN   NaN   NaN   NaN
8   NaN   NaN   NaN   NaN   NaN   NaN
9   NaN   NaN  10.0   NaN  10.0   8.0

In [51]:
## 9) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 o valores NaN. Luego llenar los valores NaN con 0.

dataFrame9 = pd.DataFrame({'A':np.random.choice([1,2,3,4,5,6,7,8,9,10, float('nan') ],10),
                       'B':np.random.choice([1,2,3,4,5,6,7,8,9,10, float('nan') ],10),
                      'C':np.random.choice([1,2,3,4,5,6,7,8,9,10, float('nan') ],10),
                      'D':np.random.choice([1,2,3,4,5,6,7,8,9,10, float('nan') ],10),
                      'E':np.random.choice([1,2,3,4,5,6,7,8,9,10, float('nan') ],10),
                      'F':np.random.choice([1,2,3,4,5,6,7,8,9,10, float('nan') ],10)})
print(dataFrame9)

dataFrame9 = dataFrame9.replace(np.nan, 0)

print('')
print(dataFrame9)


A     B     C     D    E     F
0  1.0   9.0  10.0   NaN  8.0   8.0
1  8.0   2.0   5.0   NaN  5.0   2.0
2  9.0   4.0   1.0  10.0  1.0   3.0
3  6.0   2.0   6.0   8.0  6.0  10.0
4  4.0  10.0   5.0   1.0  NaN   6.0
5  1.0   3.0   3.0   4.0  3.0   5.0
6  8.0   5.0   5.0   3.0  9.0   NaN
7  8.0  10.0  10.0   2.0  5.0   4.0
8  4.0  10.0   5.0   1.0  9.0  10.0
9  3.0   9.0   3.0  10.0  7.0   NaN

     A     B     C     D    E     F
0  1.0   9.0  10.0   0.0  8.0   8.0
1  8.0   2.0   5.0   0.0  5.0   2.0
2  9.0   4.0   1.0  10.0  1.0   3.0
3  6.0   2.0   6.0   8.0  6.0  10.0
4  4.0  10.0   5.0   1.0  0.0   6.0
5  1.0   3.0   3.0   4.0  3.0   5.0
6  8.0   5.0   5.0   3.0  9.0   0.0
7  8.0  10.0  10.0   2.0  5.0   4.0
8  4.0  10.0   5.0   1.0  9.0  10.0
9  3.0   9.0   3.0  10.0  7.0   0.0


In [52]:
## 10) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y sacar la media, la mediana, el promedio
dataFrame10 = pd.DataFrame(np.random.randint(1, 11,60).reshape(10,6), columns=list('ABCDEF'))
print(dataFrame10)

print('\n Promedio o media')
print(dataFrame10.mean())

print('\n Mediana')
print(dataFrame10.median())


A  B   C   D  E  F
0  10  8  10   5  8  7
1  10  7   3  10  6  5
2   5  8   8   3  8  7
3   4  4   2   2  4  9
4   7  6   5   2  7  4
5   7  6   6   1  1  8
6   5  9   5   3  1  3
7   4  7   9   3  7  2
8   6  3   5   3  7  4
9   1  1   2   7  5  6

 Promedio o media
A    5.9
B    5.9
C    5.5
D    3.9
E    5.4
F    5.5
dtype: float64

 Mediana
A    5.5
B    6.5
C    5.0
D    3.0
E    6.5
F    5.5
dtype: float64


In [55]:
## 11) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10, luego crear otro dateframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y anadirlo al primer Dataframe
dataFrame11_1 = pd.DataFrame(np.random.randint(1, 11,60).reshape(10,6), columns=list('ABCDEF'))
print(dataFrame11_1)
print('')
dataFrame11_2 = pd.DataFrame(np.random.randint(1, 11,60).reshape(10,6), columns=list('ABCDEF'))
print(dataFrame11_2)

print('\n Dataframe 1 y 2:')
dataFrame11_1 = dataFrame11_1.append(dataFrame11_2)
print(dataFrame11_1)


A   B  C  D   E   F
0   7   2  5  2   9   2
1   5   7  2  4   4   3
2   2   9  2  7   3  10
3   3   9  2  4  10   3
4   4   9  8  5   8   1
5   2   2  9  4   3   5
6   5   1  8  4   4   5
7  10   9  4  3   6   3
8   7   4  5  4   7   5
9   2  10  4  3   9   5

    A   B   C   D   E  F
0   2   9  10   7   7  9
1   6   9   3  10   7  8
2   8  10   9   3   4  5
3   5  10   5   4   7  2
4   8   5   2   2   7  2
5  10   2  10   9  10  4
6  10   8   2   3   9  1
7   9   1   9   1   4  9
8   7   5   6   9   5  6
9   3   6   7   4  10  9

 Dataframe 1 y 2:
    A   B   C   D   E   F
0   7   2   5   2   9   2
1   5   7   2   4   4   3
2   2   9   2   7   3  10
3   3   9   2   4  10   3
4   4   9   8   5   8   1
5   2   2   9   4   3   5
6   5   1   8   4   4   5
7  10   9   4   3   6   3
8   7   4   5   4   7   5
9   2  10   4   3   9   5
0   2   9  10   7   7   9
1   6   9   3  10   7   8
2   8  10   9   3   4   5
3   5  10   5   4   7   2
4   8   5   2   2   7   2
5  10   2  10   9  10   4
6  

In [81]:
## 12) Crear un Dataframe con 10 registros y 6 columnas llenas de strings. Luego, unir la columna 1 y 2 en una sola, la 3 y 4, y la 5 y 6 concatenando su texto.
strings = ['texto1','texto2','texto3','texto4','texto5','texto6','texto7','texto8','texto9',]

dataFrame12 = pd.DataFrame({'A':np.random.choice(strings,10),
                       'B':np.random.choice(strings,10),
                      'C':np.random.choice(strings,10),
                      'D':np.random.choice(strings,10),
                      'E':np.random.choice(strings,10),
                      'F':np.random.choice(strings,10)})

print(dataFrame12)

dataFrame12['A'] = dataFrame12['A']+dataFrame12['B']
dataFrame12['B'] = dataFrame12['C']+dataFrame12['D']
dataFrame12['C'] = dataFrame12['E']+dataFrame12['F']


print(dataFrame12)

A       B       C       D       E       F
0  texto4  texto3  texto7  texto4  texto7  texto9
1  texto3  texto8  texto6  texto9  texto5  texto3
2  texto9  texto5  texto2  texto9  texto9  texto9
3  texto2  texto7  texto7  texto8  texto4  texto7
4  texto6  texto7  texto7  texto8  texto5  texto5
5  texto6  texto9  texto1  texto6  texto5  texto5
6  texto8  texto9  texto1  texto9  texto2  texto8
7  texto9  texto6  texto4  texto7  texto8  texto4
8  texto5  texto5  texto1  texto6  texto9  texto4
9  texto7  texto4  texto9  texto6  texto7  texto3
              A             B             C       D       E       F
0  texto4texto3  texto7texto4  texto7texto9  texto4  texto7  texto9
1  texto3texto8  texto6texto9  texto5texto3  texto9  texto5  texto3
2  texto9texto5  texto2texto9  texto9texto9  texto9  texto9  texto9
3  texto2texto7  texto7texto8  texto4texto7  texto8  texto4  texto7
4  texto6texto7  texto7texto8  texto5texto5  texto8  texto5  texto5
5  texto6texto9  texto1texto6  texto5texto5  texto

In [68]:
## 13) Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 enteros, obtener la frecuencia de repeticion de los numeros enteros en cada columna

dataFrame13 = pd.DataFrame(np.random.randint(1, 11,60).reshape(10,6), columns=list('ABCDEF'))
print(dataFrame13)

for column in dataFrame13:
    print('\n Conteo columna '+column)
    print(dataFrame13[column].value_counts())


A   B  C   D   E   F
0   6   4  9   9   8   3
1   8   6  2   3   9  10
2   1   7  8   8   2  10
3   6   6  1   4   1   9
4  10  10  7   2   4   9
5   7   5  7   5   9   4
6   2   8  3   1   3   6
7   4   7  3   5   7  10
8   3   9  7   4   1   9
9   5   3  6  10  10   8

 Conteo columna A
6     2
10    1
8     1
7     1
5     1
4     1
3     1
2     1
1     1
Name: A, dtype: int64

 Conteo columna B
7     2
6     2
10    1
9     1
8     1
5     1
4     1
3     1
Name: B, dtype: int64

 Conteo columna C
7    3
3    2
9    1
8    1
6    1
2    1
1    1
Name: C, dtype: int64

 Conteo columna D
5     2
4     2
10    1
9     1
8     1
3     1
2     1
1     1
Name: D, dtype: int64

 Conteo columna E
9     2
1     2
10    1
8     1
7     1
4     1
3     1
2     1
Name: E, dtype: int64

 Conteo columna F
10    3
9     3
8     1
6     1
4     1
3     1
Name: F, dtype: int64


In [80]:
## 14) Crear un Dataframe con 10 registros y 3 columnas, A B C, llenas de números randomicos del 1 al 10 enteros. Crear una nueva columna con el calculo por fila (A * B ) / C

dataFrame14 = pd.DataFrame(np.random.randint(1, 11,30).reshape(10,3), columns=list('ABC'))
print(dataFrame14)

dataFrame14['calculada'] = (dataFrame14['A'] * dataFrame14['B'] ) /  dataFrame14['C']
print(dataFrame14)

A   B  C
0   6  10  5
1   9   1  1
2   5  10  6
3   9   6  9
4   3   8  5
5   3   3  9
6  10   3  2
7   5   5  1
8   5   2  8
9   5   8  4
    A   B  C  calculada
0   6  10  5  12.000000
1   9   1  1   9.000000
2   5  10  6   8.333333
3   9   6  9   6.000000
4   3   8  5   4.800000
5   3   3  9   1.000000
6  10   3  2  15.000000
7   5   5  1  25.000000
8   5   2  8   1.250000
9   5   8  4  10.000000
