In [1]:
import numpy as np

In [2]:
arreglo_grados = np.array([0,30,45,60,90])

In [3]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [4]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
numero_random = np.random.randint(
    11 #[0, 11[
)
numero_random

0

In [8]:
numero_random = np.random.randint(
    -9, #[-9, 2[
    2
)
numero_random

-4

In [11]:
arreglo_random = np.random.randint(
    10, #[-9, 2[
    20,
    8
)
arreglo_random

array([14, 19, 17, 18, 16, 11, 16, 10])

In [13]:
np.random.rand(9)
np.random.rand(3,2)

array([[0.55240895, 0.1919578 ],
       [0.3394357 , 0.19338015],
       [0.52409475, 0.67243689]])

In [15]:
np.average(arreglo_random) #promedio

15.125

In [16]:
np.mean(arreglo_random) #media

15.125

In [17]:
np.median(arreglo_random) #mediana

16.0

In [18]:
np.std(arreglo_random) #desviacion estandar

3.018174116912409

In [19]:
np.var(arreglo_random) #varianza

9.109375

In [20]:
arreglo_random.mean()

15.125