In [1]:
import numpy as np

In [3]:
arreglo = np.arange(11) ** 2
arreglo

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [4]:
arreglo[0:7]

array([ 0,  1,  4,  9, 16, 25, 36])

In [6]:
arreglo[-6:-1]

array([25, 36, 49, 64, 81])

In [7]:
arreglo[2:-3]

array([ 4,  9, 16, 25, 36, 49])

In [8]:
arreglo[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
arreglo[:-3]

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [10]:
arreglo[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
arreglo[0:6]

array([ 0,  1,  4,  9, 16, 25])

In [12]:
arreglo[0:6:2]

array([ 0,  4, 16])

In [13]:
arreglo[::2]

array([  0,   4,  16,  36,  64, 100])

In [15]:
arreglo[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])