In [2]:
# 1) Examen
import numpy as np

In [4]:
## 2) Crear un vector de ceros de tamaño 10
vector_zeros = np.zeros(10)
vector_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
vector_zeros = np.zeros(10)
vector_zeros[4] = 1
vector_zeros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.
vector_zeros = np.arange(50)
vector_zeros = vector_zeros[::-1]
vector_zeros



array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [11]:
## 5) Crear una matriz de 3 x 3 con valores del cero al 8
vectorN = np.arange(9)
vectorN.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
## 6) Encontrar los indices que no sean cero en un arreglo
arreglo = [1,2,0,0,4,0]
arreglo = np.array(arreglo)
muestra = arreglo != 0
arreglo[muestra]

array([1, 2, 4])

In [30]:
## 7) Crear una matriz de identidad 3 x 3 
matriz_identidad = np.identity(3)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
## 8) Crear una matriz 3 x 3 x 3 con valores randomicos
arreglo_random = np.random.randint(
    10, #[-9, 2[
    20,
    [3,3,3]
)
arreglo_random

array([[[17, 19, 18],
        [16, 15, 15],
        [16, 19, 13]],

       [[14, 19, 10],
        [18, 14, 17],
        [11, 15, 14]],

       [[13, 13, 10],
        [15, 14, 16],
        [19, 15, 12]]])

In [42]:
## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor
arreglo_random = np.random.randint(
    0, #[-9, 2[
    100,
    [10,10]
)
print(arreglo_random)
print(arreglo_random.min())
print(arreglo_random.max())

[[ 1 58 43 81 59 62 70 65 62 16]
 [75 82 32 58 75 16 95 39 71 85]
 [92 83 11 56 24 85 92 38 89 73]
 [11 88 96 24 18 58 86 84 89 19]
 [84 15 90 42  1 19 23 79  8 53]
 [62 30 39  5 25 80 91 46 71 95]
 [10 83 92 24 88 45 41 90 39 56]
 [68 59 11 45 39 37 58 99 61 88]
 [68 98 52 47 94 45 49 57 20 52]
 [ 1 99 52 50 75 13 98 69 55 60]]
1
99


In [62]:
## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)
from scipy import ndimage,misc
mapache = misc.face()
unicos = np.unique(mapache)
print(f"{len(unicos)} colores")

256 colores


In [70]:
## 11) ¿Como crear una serie de una lista, diccionario o arreglo?
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
serieLista = pd.Series(mylist)
serieArreglo = pd.Series(myarr)
serieDict = pd.Series(mydict)

In [72]:
## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
dataFrame = pd.DataFrame(data=ser)
dataFrame

0
a   0
b   1
c   2
e   3
d   4
f   5
g   6
h   7
i   8
j   9
k  10
l  11
m  12
n  13
o  14
p  15
q  16
r  17
s  18
t  19
u  20
v  21
w  22
x  23
y  24
z  25

In [76]:
## 13) ¿Como combinar varias series para hacer un DataFrame?

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
dataFrame = pd.DataFrame(data=[ser1,ser2])
dataFrame

0  1  2  3  4  5  6  7  8  9   ...  16  17  18  19  20  21  22  23  24  25
0  a  b  c  e  d  f  g  h  i  j  ...   q   r   s   t   u   v   w   x   y   z
1  0  1  2  3  4  5  6  7  8  9  ...  16  17  18  19  20  21  22  23  24  25

[2 rows x 26 columns]

In [123]:
## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
result = ser1[~ser1.isin(ser2)]
print(result)

0    1
1    2
2    3
dtype: int64


In [128]:
## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
sr11 = pd.Series(np.union1d(ser1, ser2))
sr22 = pd.Series(np.intersect1d(ser1, ser2))
result = sr11[~sr11.isin(sr22)]
print(result)

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64


In [133]:
## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

d    7
e    5
c    4
g    4
a    3
b    3
h    2
f    2
dtype: int64

In [165]:
## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [5]))
mas_repetidos = ser.value_counts()
print(mas_repetidos)
print(ser)

print(ser.replace(mas_repetidos,0))


3    2
2    2
dtype: int64
0    3
1    2
2    4
3    2
4    3
dtype: int64
0    3
1    2
2    4
3    0
4    3
dtype: int64


In [175]:
## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?

ser = pd.Series(np.random.randint(1, 10, 35))

dataFrame = pd.DataFrame(data=ser)
dataFrame

0
0   1
1   4
2   4
3   1
4   4
5   9
6   3
7   3
8   4
9   4
10  9
11  8
12  4
13  3
14  1
15  7
16  2
17  7
18  6
19  3
20  6
21  2
22  6
23  4
24  2
25  3
26  8
27  4
28  6
29  3
30  6
31  8
32  7
33  4
34  8

In [176]:
## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u


In [ ]:
## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))